import 'dart:convert';

import 'package:primordis/sim/parity/frame_metrics.dart';
import 'package:primordis/sim/parity/parity_bands.dart';
import 'package:primordis/sim/parity/parity_metrics.dart';

/// A time series of [FrameMetrics] sampled at named steps of one run.
///
/// This is the committable, comparable *fingerprint* of a backend (or the
/// reference): a fixed set of named checkpoints — e.g. `early`, `mid`,
/// `steady` — each carrying the full aggregate statistics at that step. Two
/// fingerprints from different backends are compared checkpoint-by-checkpoint
/// under a [ParityBands] preset.
///
/// It serialises to/from JSON so the reference fingerprint can be committed as a
/// fixture and regenerated by tooling (see `tool/parity/`), and so a golden
/// baseline is a plain diffable file.
class ParityFingerprint {
  const ParityFingerprint({
    required this.label,
    required this.seed,
    required this.particleCount,
    required this.typeCount,
    required this.attractionK,
    required this.repulsionK,
    required this.friction,
    required this.checkpoints,
  });

  /// Human-readable name of the source (e.g. `cpu`, `wgsl-kernel`, `reference`).
  final String label;

  /// The RNG seed the run started from.
  final int seed;

  /// Particle population (constant across the run).
  final int particleCount;

  /// Number of particle types.
  final int typeCount;

  /// The three live slider values the run used, recorded so a fingerprint
  /// captured at a non-default (Attraction, Repulsion, Drift) setting is
  /// self-describing and only compared against a matching-parameter reference.
  final double attractionK;
  final double repulsionK;
  final double friction;

  /// Named checkpoints → the frame metrics at that step. Insertion order is the
  /// simulation order (`early`, `mid`, `steady`, ...).
  final Map<String, FrameMetrics> checkpoints;

  /// Compares this fingerprint against a [reference] under [bands].
  ///
  /// Returns an empty list when every checkpoint's every metric is within band.
  /// Otherwise each entry is prefixed with the checkpoint name and the source
  /// labels, so a failure reads e.g.
  /// `[steady] cpu vs reference — speed.mean: observed ...`.
  ///
  /// Checkpoints present in [reference] but missing here (or vice versa) are
  /// reported as structural mismatches rather than silently skipped.
  List<String> violationsAgainst(
    ParityFingerprint reference,
    ParityBands bands,
  ) {
    final failures = <String>[];
    for (final name in reference.checkpoints.keys) {
      final ref = reference.checkpoints[name];
      final obs = checkpoints[name];
      if (obs == null) {
        failures.add('[$name] $label is missing checkpoint present in '
            '${reference.label}');
        continue;
      }
      for (final v in bands.violations(ref!, obs)) {
        failures.add('[$name] $label vs ${reference.label} — $v');
      }
    }
    for (final name in checkpoints.keys) {
      if (!reference.checkpoints.containsKey(name)) {
        failures.add('[$name] $label has an extra checkpoint absent from '
            '${reference.label}');
      }
    }
    return failures;
  }

  /// A stable, human-diffable JSON form. Doubles are emitted at full precision
  /// so a regenerated fixture round-trips exactly.
  Map<String, dynamic> toJson() => <String, dynamic>{
        'label': label,
        'seed': seed,
        'particleCount': particleCount,
        'typeCount': typeCount,
        'attractionK': attractionK,
        'repulsionK': repulsionK,
        'friction': friction,
        'checkpoints': <String, dynamic>{
          for (final entry in checkpoints.entries)
            entry.key: _frameToJson(entry.value),
        },
      };

  /// Pretty-printed JSON suitable for committing as a fixture.
  String toPrettyJson() =>
      const JsonEncoder.withIndent('  ').convert(toJson());

  /// Rebuilds a fingerprint from its [toJson] form.
  factory ParityFingerprint.fromJson(Map<String, dynamic> json) {
    final rawCheckpoints = json['checkpoints'] as Map<String, dynamic>;
    return ParityFingerprint(
      label: json['label'] as String,
      seed: (json['seed'] as num).toInt(),
      particleCount: (json['particleCount'] as num).toInt(),
      typeCount: (json['typeCount'] as num).toInt(),
      attractionK: (json['attractionK'] as num).toDouble(),
      repulsionK: (json['repulsionK'] as num).toDouble(),
      friction: (json['friction'] as num).toDouble(),
      checkpoints: <String, FrameMetrics>{
        for (final entry in rawCheckpoints.entries)
          entry.key: _frameFromJson(entry.value as Map<String, dynamic>),
      },
    );
  }

  static Map<String, dynamic> _frameToJson(FrameMetrics m) => <String, dynamic>{
        'particleCount': m.particleCount,
        'clusterCount': m.clusterCount,
        'occupiedBinFraction': m.occupiedBinFraction,
        'occupancy': _momentsToJson(m.occupancy),
        'nearestNeighbour': _momentsToJson(m.nearestNeighbour),
        'segregationIndex': m.segregationIndex,
        'speed': _momentsToJson(m.speed),
        'kineticEnergy': m.kineticEnergy,
        'maxEdgeBinExcess': m.maxEdgeBinExcess,
      };

  static FrameMetrics _frameFromJson(Map<String, dynamic> json) => FrameMetrics(
        particleCount: (json['particleCount'] as num).toInt(),
        clusterCount: (json['clusterCount'] as num).toInt(),
        occupiedBinFraction: (json['occupiedBinFraction'] as num).toDouble(),
        occupancy: _momentsFromJson(json['occupancy'] as Map<String, dynamic>),
        nearestNeighbour:
            _momentsFromJson(json['nearestNeighbour'] as Map<String, dynamic>),
        segregationIndex: (json['segregationIndex'] as num).toDouble(),
        speed: _momentsFromJson(json['speed'] as Map<String, dynamic>),
        kineticEnergy: (json['kineticEnergy'] as num).toDouble(),
        maxEdgeBinExcess: (json['maxEdgeBinExcess'] as num).toDouble(),
      );

  static Map<String, dynamic> _momentsToJson(Moments m) => <String, dynamic>{
        'count': m.count,
        'mean': m.mean,
        'variance': m.variance,
        'min': m.min,
        'max': m.max,
      };

  static Moments _momentsFromJson(Map<String, dynamic> json) => Moments(
        count: (json['count'] as num).toInt(),
        mean: (json['mean'] as num).toDouble(),
        variance: (json['variance'] as num).toDouble(),
        min: (json['min'] as num).toDouble(),
        max: (json['max'] as num).toDouble(),
      );
}
